### ISSUE TITLE
Documentation site is down.

### ISSUE THREAD

**Issue by TheWaffleDimension** [CrescentCode/Freya#11]

**Comment by eLunate** [comment]
Unfortunately I effectively abandoned Freya and Roblox, and then stopped paying for the server which was hosting the Enchiridion. If you still plan on using Freya, the raw docs are [here](https://github.com/CrescentCode/Enchiridion/tree/master/site/Freya).

Given the resistance to it that I saw during the time when I was maintaining it, I will not be maintaining Freya any more. If the development ethics change in Roblox, I may resume official development/maintenance of Freya.

Feel free to fork and maintain your own version of Freya if you wish.
