### ISSUE TITLE
Input component: InputDirection.Changed (and aliases) not working

### ISSUE THREAD

**Issue by DireMitten** [CrescentCode/Freya#2]
Example:

`local TestAction = Input:CreateAction(
	"TestAction",
	function(InputState, GameProcessedEvent, RawInput)
		print(InputState.Key, InputState.Down)
	end
); TestAction:BindControl(Input.InputSources.Keyboard.W, Input.InputDirections.Changed)`

Will do nothing when the 'W' key is pressed. Changing the InputDirection to 'Up' or 'Down' or 'DownUp' makes it work as expected. I've not tested it with the 'Action' InputDirection.

No errors are printed to the console

**Comment by eLunate** [comment]
The idea is that you don't need Changed, because we already use the action states. As a result, Changed should only fire for states which have no 'up/down' state or only transitional states. If you need both up and down being bound, you will need to bind the action to both directions.

**Comment by eLunate** [comment]
Changed will fire when moving the mouse, for example, and some other states. It's a nuance defined by UIS, rather than Freya Input.

**Comment by eLunate** [comment]
If you need a catch-all for an input, I can add an InputDirection.Any?

**Comment by DireMitten** [comment]
Ah, I see. Thanks for clearing that up. Binding the action to both the Up and Down direction works perfectly. I think the confusion arose because I'm used to using UserInputService, which also has a .Changed event, which fires when the mouse moves, or a keyboard button changes state, or anything else along those lines. 

I don't *need* another InputDirection, and I don't think it would be helpful. I would just have to have more conditionals in my ActionCallback functions, so I wouldn't save much typing.

**Comment by eLunate** [comment]
Good to know that's all cleared up.
