### ISSUE TITLE
Issues with installing Freya

### ISSUE THREAD

**Issue by jackyloz** [CrescentCode/Freya#4]
14:29:59.522 - Requested module experienced an error while loading
14:29:59.523 - Stack Begin
14:29:59.523 - Script 'require(480740831)', Line 1
14:29:59.523 - Stack End

**Comment by eLunate** [comment]
Fixed. Had a small problem with the CI; it builds and uploads empty modules sometimes.

**Comment by jackyloz** [comment]
It appears that it's not fixed.

**Comment by eLunate** [comment]
That one is. The CI says it's updated, and I've had people (including myself) installing it successfully within the past 3 hours. Try for a clean install just in case.

**Comment by jackyloz** [comment]
Running the require line in my command bar doesn't work and says it experienced an error.

**Comment by eLunate** [comment]
I've just tested on Studio, and both an upgrade and a clean install run without errors. If you have Freya currently installed, try deleting ReplicatedStorage/Freya/Util/RepoManager as it appears to be causing problems in some cases.

**Comment by Gskartwii** [comment]
Roblox caches assets it loads in Studio. To properly load the model, you need to restart Studio or open a new place file.
